// ============================================================
// Save as: scripts/generate-readme.js
//
// Run locally to test: node scripts/generate-readme.js
// ============================================================

const https = require('https');
const fs    = require('fs');
const path  = require('path');

// ── Configuration ─────────────────────────────────────────────
const USERNAME   = process.env.GITHUB_USERNAME || 'Yuvadi29';  // ← Change this
const REPO_NAME  = 'Github-Actions-Series';                                // ← Change this
const BLOG_URL   = 'https://codingadda.hashnode.dev/';                // ← Change this (or leave blank)
const TOKEN      = process.env.GITHUB_TOKEN;

// ── Simple HTTP helper ────────────────────────────────────────
function get(url, headers = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'readme-bot', ...headers } }, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => resolve(body));
    }).on('error', reject);
  });
}

// ── Fetch GitHub stats for your repo ─────────────────────────
async function getStats() {
  try {
    const headers = TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {};
    const data    = JSON.parse(await get(`https://api.github.com/repos/${USERNAME}/${REPO_NAME}`, headers));
    return {
      stars  : data.stargazers_count || 0,
      forks  : data.forks_count      || 0,
      issues : data.open_issues_count || 0,
    };
  } catch (e) {
    console.warn('Could not fetch stats:', e.message);
    return { stars: 0, forks: 0, issues: 0 };
  }
}

// ── Fetch latest blog posts from RSS feed ────────────────────
async function getPosts() {
  try {
    const xml   = await get(`${BLOG_URL}/rss.xml`);
    const posts = [];
    const regex = /<item>([\s\S]*?)<\/item>/g;
    let   match;

    while ((match = regex.exec(xml)) && posts.length < 5) {
      const block = match[1];
      const title = (/<title><!\[CDATA\[(.*?)\]\]>/.exec(block) || /<title>(.*?)<\/title>/.exec(block))?.[1];
      const link  = /<link>(.*?)<\/link>/.exec(block)?.[1];
      if (title && link) posts.push({ title: title.trim(), link: link.trim() });
    }
    return posts;
  } catch (e) {
    console.warn('Could not fetch blog posts:', e.message);
    return [];
  }
}

// ── Build the README content ──────────────────────────────────
async function run() {
  console.log('Fetching GitHub stats...');
  const stats = await getStats();

  console.log('Fetching blog posts...');
  const posts = await getPosts();

  const updatedAt = new Date().toUTCString();

  const content = `<!-- Auto-generated by GitHub Actions — do not edit manually -->
<!-- Last updated: ${updatedAt} -->

<div align="center">

# 👋 Hey, I'm ${USERNAME}!

### Welcome to my GitHub Profile

[![YouTube](https://img.shields.io/badge/YouTube-Coding_Adda-red?style=for-the-badge&logo=youtube)](https://youtube.com/@coding_adda)
[![GitHub followers](https://img.shields.io/github/followers/${USERNAME}?style=for-the-badge)](https://github.com/${USERNAME})

</div>

---

## 📊 ${REPO_NAME} Stats

| ⭐ Stars | 🍴 Forks | 🐛 Open Issues |
|:---:|:---:|:---:|
| ${stats.stars} | ${stats.forks} | ${stats.issues} |

---

## 📝 Latest Blog Posts

${posts.length > 0
  ? posts.map(p => `- [${p.title}](${p.link})`).join('\n')
  : '> No blog posts found. Add your RSS URL to the script!'}

---

## 🚀 What I Do

- 🎥 I create programming tutorials on [Coding Adda](https://youtube.com/@coding_adda)
- 💻 I write about GitHub Actions, Docker, CI/CD, and Web Development
- 🌱 Currently learning: AI/ML and Cloud Infrastructure

---

<div align="center">

*This README is updated automatically every day using GitHub Actions.*
*Last refresh: ${updatedAt}*

</div>
`;

  const outputPath = path.join(process.cwd(), 'README.md');
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`✅ README.md written! (Stars: ${stats.stars}, Posts: ${posts.length})`);
}

run().catch(err => {
  console.error('❌ Script failed:', err.message);
  process.exit(1);
});